[project]
name = 'Supply-Chain-Emissions-Tracking-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.green-achievement-nft]
path = 'contracts/green-achievement-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.reduction-targets]
path = 'contracts/reduction-targets.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
